### ISSUE TITLE
[JOSS Review] - Community guidelines

### ISSUE THREAD

**Issue by ericfell** [mxwalbert/cohesivm#2]
Dear authors,

Thank you for including a `CONTRIBUTING.md`. 
Can you also add a **Contributing** section somewhere in `docs` (so that it appears on readthedocs) to improve the visibility for third parties looking to contribute? This could paraphrase `CONTRIBUTING.md` or just provide a link to it. Often this appears in a FAQ page in readthedocs.

This issue is related to openjournals/joss-reviews#7291

**Comment by mxwalbert** [comment]
Dear @ericfell,
we added a "Getting Involved" section in the documenation and put the contributiong guidelines and contact information there. Furthermore, we added invitations for contributions in the implementation tutorials in the readthedocs documentation.
