### ISSUE TITLE
[JOSS Review] - dependencies section in README

### ISSUE THREAD

**Issue by ericfell** [mxwalbert/cohesivm#5]
Dear authors,

Can you also provide a **Dependencies** section in your root `README.md` listing the core dependencies? I find it most useful on a project `README` to quickly see which version(s) of Python is required.

This issue is related to openjournals/joss-reviews#7291

**Comment by mxwalbert** [comment]
Dear @ericfell,
we added a dependencies section and included information about the available extras. We also added notes in the GUI descriptions, referring to the required ``gui`` extra.
