### ISSUE TITLE
[JOSS Review] - Docs and tests

### ISSUE THREAD

**Issue by enricgrau** [mxwalbert/cohesivm#7]
Overall, the documentation looks good. It is clear and easy to follow and contains all the necessary sections to manage the library. Tests run smoothly and are comprehensive. I only have two minor observations:

- `test/test_measurements/test_cv.py` is empty. There is no reference to this file in the `docs`. If this is on purpose please indicate why. Otherwise, you should probably populate or remove it.
- There is no versioning. Please consider making versions with change logs.

**Comment by mxwalbert** [comment]
Dear @enricgrau,
thank you for noticing this! We removed the unused file and created the initial release in the repository.
